CREATE TABLE wp_ipc_projects
(
    CaseReference                                    varchar(10) NOT NULL,
    ProjectName                                      text,
    Proposal                                         text,
    Summary                                          text,
    Stage                                            tinyint     NOT NULL,
    PromoterName                                     text,
    PromoterFirstName                                text,
    PromoterLastName                                 text,
    ApplicantEmailAddress                            text,
    ApplicantPhoneNumber                             text,
    WebAddress                                       text,
    ProjectEmailAddress                              text,
    Region                                           text,
    ProjectLocation                                  text,
    AnticipatedGridRefEasting                        float       DEFAULT NULL,
    AnticipatedGridRefNorthing                       float       DEFAULT NULL,
    MapZoomLevel                                     text,
    AnticipatedDateOfSubmission                      text,
    AnticipatedSubmissionDateNonSpecific             text,
    DateOfDCOSubmission                              date        DEFAULT NULL,
    DateOfDCOAcceptance_NonAcceptance                date        DEFAULT NULL,
    DateOfPreliminaryMeeting                         text,
    ConfirmedStartOfExamination                      text,
    DateTimeExaminationEnds                          datetime    DEFAULT NULL,
    DateOfRepresentationPeriodOpen                   date        DEFAULT NULL,
    DateOfRelevantRepresentationClose                date        DEFAULT NULL,
    DateRRepAppearOnWebsite                          date        DEFAULT NULL,
    Stage4ExtensiontoExamCloseDate                   text,
    Stage5ExtensiontoRecommendationDeadline          text,
    Stage5ExtensiontoDecisionDeadline                text,
    DateOfRecommendations                            text,
    ConfirmedDateOfDecision                          text,
    DateProjectWithdrawn                             text,
    sourceSystem                                     varchar(15) DEFAULT NULL,
    dateOfNonAcceptance                              datetime    DEFAULT NULL,
    Documents                                        text,
    LatLong                                          text,
    ApplicantDescriptionOfProject                    text,
    CaseLeaderName                                   text,
    Commissioner                                     text,
    DateProjectAppearsOnWebsite                      text,
    DateOfDCOAcceptance                              text,
    PromotersPublicity                               text,
    StartDateOfPeriodforCommentsOnRelevantReps       date        DEFAULT NULL,
    PeriodOfCommentsOnRelevantRepresentationsEnds    date        DEFAULT NULL,
    DateDetailedRepresentationsPeriodOpens           date        DEFAULT NULL,
    DateDetailedRepresentationsPeriodClose           date        DEFAULT NULL,
    DateCommentsOnDetailedRepresentationsPeriodOpens date        DEFAULT NULL,
    DateCommentsOnDetailedRepresentationsClose       date        DEFAULT NULL,
    DateOfReceivingLIR                               date        DEFAULT NULL,
    DeadlineForLIR                                   date        DEFAULT NULL,
    DateCommentsPeriodofLIROpens                     date        DEFAULT NULL,
    DateCommentsPeriodofLIRCloses                    date        DEFAULT NULL,
    DateOfNextExaminationHearing                     date        DEFAULT NULL,
    NotesRegardingNextExaminationHearing             text,
    DescriptionOfLocation                            text,
    SingleOrLinear                                   text,
    StartGridE                                       varchar(45) DEFAULT NULL,
    StartGridN                                       varchar(45) DEFAULT NULL,
    MiddleGridE                                      varchar(45) DEFAULT NULL,
    MiddleGridN                                      varchar(45) DEFAULT NULL,
    EndGridE                                         varchar(45) DEFAULT NULL,
    EndGridN                                         varchar(45) DEFAULT NULL,
    Modified                                         varchar(45) DEFAULT NULL,
    DateOfCommissionerAppointment                    date        DEFAULT NULL,
    TimeOfRelevantRepresentationClose                datetime    DEFAULT NULL,
    TwitterAccountName                               varchar(45) DEFAULT NULL,
    SINumber                                         int         DEFAULT NULL,
    CaseSubType                                      varchar(45) DEFAULT NULL,
    PRIMARY KEY (CaseReference)
);

INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN010009', 'St James Barton Giant Wind Turbine', 'EN01 - Generating Stations',
        'St James Barton, BRISTOL THU 16 JAN', 3, 'Horizon Dev Environment DJW', 'Postman', 'Pat',
        'david.white@pins.gsi.gov.uk', '1234', NULL,
        '\"The Windmill of the South!\" - Tue 14 Jan 2020, 17 May 2021 DJW test on NSIP Azure website Also in TestAZ Giant wind turbine on St James Barton roundabout.',
        'david.white@pins.gsi.gov.uk', NULL, NULL, NULL, 'Long— –dash', NULL, NULL, NULL, '2017-02-14', '2024-08-01',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, '', NULL, 347128, 176491, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShowSubmissionsTab',
        '51.48441200795, -2.7615229238543', 'South West', '2015-12-10', NULL, '', '2021-09-29 10:00:06', '2017-08-01', NULL,
        NULL, NULL, NULL, NULL, NULL, 'HORIZON', '2022-11-30 00:00:00', 'mc');
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN010011', 'Rookery South Energy from Waste Generating Station', 'EN01 - Generating Stations',
        'Rookery South Pit, Near Stewartby, Bedfordshire', 7, 'Covanta Rookery South Limited', 'Robin', 'Treacher',
        'webteam@planninginspectorate.gov.uk', '08449671101', NULL,
        'Energy from Waste facility with a gross electrical output capacity of 65 MWe.',
        'nienquiries@planninginspectorate.gov.uk', NULL, NULL, '2010-07-05', '', NULL, NULL, NULL, '2010-10-07',
        '2010-11-19', NULL, NULL, NULL, '2011-01-18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        '2011-10-13', NULL, NULL, NULL, NULL, 'County', NULL, 501803, 241158, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        'archive', '52.059018720845, -0.51494723713858', 'Eastern', '2010-08-05', '2010-08-26', '',
        '2019-12-18 12:12:15', '2010-11-26', NULL, '2011-07-15 00:00:00', NULL, NULL, NULL, NULL, NULL,
        '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN010102', 'Hinkley Point C New Nuclear Power Station Material Change 1', 'EN01 - Generating Stations',
        'Approximately 3km offshore of Hinkley Point, Somerset', 3, 'NNB Generation Company (HPC) Limited', 'Carly',
        'Vince', 'webteam@planninginspectorate.gov.uk', '0800 197 6102', NULL,
        'Removal of requirement to install Acoustic Fish Deterrent system (associated with cooling water intake heads)',
        NULL, NULL, NULL, NULL, 'Q2 2019', NULL, NULL, NULL, '2022-09-14', '2022-12-21', NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 321217, 146033,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mc', '51.207547796017, -3.1279139292638', 'South West', '2021-01-01',
        NULL, 'www.edfenergy.com', '2021-06-22 15:07:46', '2023-01-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN010116', 'North Lincolnshire Green Energy Park', 'EN01 - Generating Stations',
        'Flixborough Wharf, Flixborough Industrial Estate, North Lincolnshire.       ', 3,
        'North Lincolnshire Green Energy Park Limited', '', '', 'chris.bungay@planninginspectorate.gov.uk', '', NULL,
        'The Project consists of an Energy Recovery Facility (ERF) converting up to 650,000 tonnes per annum of Refuse Derived Fuel (RDF) to generate a maximum of 95 Mega Watts of electrical output (MWe) and/or 380 Mega Watts of thermal output (MWt) to provide power, heat and steam on the site of the operating Flixborough Wharf on the River Trent. The Project will incorporate battery storage, hydrogen production from the electrolysis of water, hydrogen storage, heat and steam storage. It will also include heat-treatment of bottom and fly ash, concrete block manufacturing, carbon dioxide capture and utilisation and an extended district heat network of 5km, power and gas network to service the nearby proposed housing development. Development at the site will also include the following associated measures to allow access to and from the site by road, rail or river, with a correspondingly reduced environmental impact: i. an extension to Flixborough Wharf; ii. the reopening of a 9km single track railway line that connects Flixborough Wharf with the steel works at Scunthorpe; iii. a railhead complex to handle the RDF and concrete products; and iv. a new road alignment to facilitate the flow of traffic accessing the site from the south.',
        'webteam@planninginspectorate.gov.uk', NULL, NULL, NULL, 'Q3 2021', NULL, NULL, '2023-01-01', '2023-08-01',
        '2025-08-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, 'Region', NULL, 485899, 414508, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        '53.620078025496,-0.70283147423378', 'Yorkshire and the Humber', NULL, NULL,
        'https://northlincolnshiregreenenergypark.co.uk/', '2021-10-26 10:32:16', NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN013007', 'Horfield Wheelabrator', 'EN01 - Generating Stations', 'Just north of Filton', 4,
        'RiverOak Strategic Partners', NULL, 'RiverOak Strategic Partners', 'manston@bdb-law.co.uk', '07717802935',
        NULL, 'A gurt big wheel thingy that\'s got brass knobs on', 'JCBEnquiries@planninginspectorate.gov.uk', NULL,
        NULL, NULL, 'who knows? Not me matey', NULL, NULL, NULL, '2020-02-17', '2020-02-18', NULL, NULL, '2020-01-12',
        '2020-01-11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-01-20', NULL,
        '2020-01-30', 'Region', NULL, 358603, 166000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShowSubmissionsTab',
        '51.391032377451, -2.5950307828278', 'South West', '2020-01-01', '2020-01-02', 'itv.co.uk',
        '2020-02-17 11:25:38', '2020-01-06', NULL, '2020-02-29 12:00:00', NULL, NULL, NULL, NULL, 'Picaso',
        '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN013009', 'Pen Test Case 1 - DO NOT MODIFY', 'EN01 - Generating Stations', 'Bristol', 3, 'PenTesting', NULL,
        'PenTesting', 'somewhere@somewhere.com', '+447852736752', NULL,
        'This is a pen test project covering the pre-examination phase to allow for registration as an interested party.',
        'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-01-01', NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        'Region', NULL, 354843, 155506, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        '51.296381681912, -2.6477409671016', 'South West', NULL, '2020-01-01', 'www.google.co.uk',
        '2020-02-24 11:44:15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Picaso', '2020-01-01 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN013012', 'Filton Wheelabrator', 'EN01 - Generating Stations', 'Just north of Filton Station', 4,
        'RiverOak Strategic Partners', NULL, 'RiverOak Strategic Partners', 'manston@bdb-law.co.uk', '07717802935',
        NULL, 'Another gurt big wheelie thing that churns out energy at a rate of Watts',
        'webteam@planninginspectorate.gov.uk', NULL, NULL, NULL, 'who knows? Not me matey', NULL, NULL, NULL,
        '2020-02-17', '2020-03-19', NULL, NULL, '2019-08-11', '2019-08-12', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, '2020-03-25', NULL, NULL, NULL, NULL, 'Country', NULL, 381454, 166652, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, 'ShowSubmissionsTab', '51.39810290405, -2.2666161136124', 'South West', '2020-10-01',
        '2020-02-01', 'bbc.co.uk', '2021-07-27 12:20:02', '2020-03-01', NULL, '2020-03-02 12:00:00', NULL, NULL, NULL,
        NULL, 'Picaso', '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN013013', 'Corby Power Station', 'EN01 - Generating Stations', 'Midlands', 4, 'Trevors Test PLC', NULL,
        'Trevors Test PLC', 'FredFlintstone@Gmail.com', '07889123456', NULL, 'Power generation station',
        'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-24', '2020-02-25',
        NULL, NULL, '2020-02-26', '2020-03-02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, 'County', NULL, 490413, 280299, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        'ShowSubmissionsTab', '52.412832402481, -0.67057588190404', 'West Midlands', '2020-02-24', NULL,
        'www.bbc.co.uk', '2020-03-12 11:07:46', '2020-02-24', NULL, NULL, NULL, NULL, NULL, NULL, 'Picaso',
        '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN013014', 'Kettering Hydrogen Power Station', 'EN01 - Generating Stations', 'Midlands', 3,
        'Test Organisation', NULL, 'Test Organisation', 'vijaya.vasantha@planninginspectorate.gov.uk', '01234567890',
        NULL, 'Kettering hydrogen power station', 'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, '2020-03-03', '2020-03-03', NULL, NULL, NULL, '2020-03-04', NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 490413, 280299, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, '52.412832402481, -0.67057588190404', 'East Midlands', '2020-03-04', NULL,
        'www.bbc.co.uk', '2020-03-04 08:04:56', '2020-03-04', NULL, NULL, NULL, NULL, NULL, NULL, 'Picaso',
        '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN033005', 'Feb 14 2020', 'EN03 - Underground Gas Storage Facilities', 'Leeds', 4, 'Champ Kadaba', NULL,
        'Champ Kadaba', 'champ.kadaba@planninginspectorate.gov.uk', '07912293353', NULL,
        'This is a Leeds test on Feb 14 2020', 'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, '2020-02-17', '2020-02-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Region', NULL, 544315, 181829, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, 'ShowSubmissionsTab', '51.516442093532, 0.080136007943624', 'North East', NULL, NULL, 'bbc.co.uk',
        '2020-02-18 09:13:12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Picaso', '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN043005', 'March 18 2020', 'EN04 - LNG Facilities', 'Bristol', 4, 'Champ Kadaba', NULL, 'Champ Kadaba',
        'champ.kadaba@planninginspectorate.gov.uk', '07912293353', NULL,
        'This is a NI Case created to test S55 letters and other documents', 'NIEnquiries@planninginspectorate.gov.uk',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-03-18', '2020-03-20', NULL, NULL, NULL, '2020-03-17', NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Borough', NULL, 544315,
        863536, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '57.63885140328, 0.41775067486792', 'South West', NULL,
        '2020-03-11', 'google.com', '2020-03-24 13:59:45', '2020-03-23', NULL, '2020-03-25 12:00:00', NULL, NULL, NULL,
        NULL, 'Picaso', '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN043006', 'Cotham Wheelabrator', 'EN04 - LNG Facilities', 'Near Kingsdown Parade', 4,
        'Test Organisation for John', NULL, 'Test Organisation for John', 'vijaya.vasantha@planninginspectorate.gov.uk',
        '07111111111', NULL, 'Yet another gurt big wheelie thing-a -me-bob', 'NIEnquiries@planninginspectorate.gov.uk',
        NULL, NULL, NULL, 'who knows? Not me matey', NULL, '0002-11-30', NULL, '2020-03-09', '2020-04-10', NULL, NULL,
        '2020-03-03', '2020-03-02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, 381454, 166652, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShowSubmissionsTab',
        '51.39810290405, -2.2666161136124', 'South West', '2020-01-01', '0002-11-30', 'www.bt.com',
        '2020-04-22 08:42:14', '2020-04-02', NULL, '2020-05-11 11:00:00', '2020-08-08', NULL, NULL, NULL, 'Picaso',
        '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN053001', 'Feb 19 2020', 'EN05 - Gas Reception Facilities', 'Holla', 4, 'John Author Burke', NULL,
        'John Author Burke', 'john.burke@planninginpsectorate.gov.uk', '07780955910', NULL, 'sdgfdgdfgfdgd',
        'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-19', '2020-03-06',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, 'Borough', NULL, 332083, 67890, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShowSubmissionsTab',
        '50.506264664658, -2.9578690931383', 'South West', NULL, NULL, 'google.com', '2020-02-20 09:43:02', NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, 'Picaso', '0002-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('TR010001', 'Accessibility Test', 'EN01 - Generating Stations', 'Somerset - Monday PM 23/12', 4, 'EDF', NULL,
        'lastname', '', '', NULL, 'MC 5 09-01-2019 part 3', '', NULL, NULL, '2020-01-01', '', NULL, '2019-05-05', NULL,
        '2019-05-06', '2019-05-06', NULL, NULL, '2020-01-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'county', NULL, 594934, 5636170, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, 'ShowSubmissionsTab', '100.58954279911, -11.543792740342', 'South West', '2018-01-01', '2019-06-06',
        'wp-test', '2021-07-06 15:45:21', '2019-06-06', NULL, '2021-07-07 00:00:00', NULL, NULL, NULL, NULL, 'HORIZON',
        '2019-06-06 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('TR023018', 'Heathrow 24th Runway', 'TR02 - Airports', 'London', 4, 'Heathrow PLC', NULL, 'Heathrow PLC', NULL,
        NULL, NULL, 'The building of a runway and control tower and other stuff.',
        'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-10', '2020-02-24',
        NULL, NULL, '2020-01-06', '2020-07-29', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, 'Region', NULL, 507488, 175896, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        'ShowSubmissionsTab', '51.471319407145, -0.45224644087338', 'South East', NULL, NULL,
        'www.fakeheathrow.897.biz', '2020-08-17 11:21:42', '2020-02-26', NULL, NULL, NULL, NULL, NULL, NULL, 'Picaso',
        '0002-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('TR023022', 'Submission Test March 12 2020', 'TR02 - Airports', 'Bristol', 4, 'Mark Sanders', NULL,
        'Mark Sanders', 'mark.sanders@planninginspectorate.gov.uk', '12345 123456', NULL,
        'This is a project creation to test submissions', 'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, '2020-03-05', '2020-03-17', NULL, NULL, NULL, '2020-03-04', NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'County', NULL, 66475, 77575, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, 'ShowSubmissionsTab', '50.502185883031, -6.7044402094495', 'South West',
        '2020-02-24', '2020-03-11', 'google.com', '2020-03-20 11:59:09', NULL, NULL, '2020-03-25 12:00:00', NULL, NULL,
        NULL, NULL, 'Picaso', '0002-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('TR023024', 'April 7 2020', 'TR02 - Airports', 'Bristol', 1, 'John Agent Burke', NULL, 'John Agent Burke',
        'john.burke@planninginpsectorate.gov.uk', '01179244548', NULL, 'This is a RR related testing Case',
        'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-03-30', '2020-04-10',
        NULL, NULL, NULL, '2020-03-30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, 'District', NULL, 64756, 745764, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        '56.484360139339, -7.4472854473807', 'South West', NULL, NULL, 'google.com', '2020-04-07 21:27:39',
        '2020-04-14', NULL, '2020-04-14 12:00:00', NULL, NULL, NULL, NULL, 'Picaso', '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('TR033002', 'Ho Ho Hooo', 'TR03 - Harbour Facilities', 'Bristol', 4, 'Ray Auxias', NULL, 'Ray Auxias',
        'Ray.Auxias@gmail.com.fake', '07111-966941', NULL, 'This is a test on 23rd Dec 2019',
        'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-16', '2020-02-17',
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, 'Region', NULL, 544309, 184126, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShowSubmissionsTab',
        '51.537085690759, 0.080990777209404', 'London', NULL, NULL, 'bbc.co.uk', '2020-02-17 14:30:30', NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, '0002-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('tr033005', 'Azure Performance Test', 'EN01 - Generating Stations', 'Somerset - cache test 03-02 15:44', 2,
        'EDF', NULL, 'lastname', '', '', NULL, 'MC 5 09-01-2019 part 3 Jun 2021', '', NULL, NULL, '2020-01-01', '',
        NULL, '2019-05-05', NULL, '2019-05-06', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'county', NULL, 594934, 5636170, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, 'ShowSubmissionsTab', '57.656841271173, -3.1382838893284', 'South West', '2018-01-01', '2019-06-06',
        'wp-test', '2021-06-28 16:21:21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Picaso', '2022-11-30 00:00:00',
        NULL);
INSERT INTO ipclive.wp_ipc_projects (CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                     PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                     ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                     Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                     DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                     DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                     StartDateOfPeriodforCommentsOnRelevantReps,
                                     PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                     ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                     DateDetailedRepresentationsPeriodClose,
                                     DateCommentsOnDetailedRepresentationsPeriodOpens,
                                     DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                     DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                     DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                     ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                     Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                     DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                     SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                     EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                     DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                     DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                     Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                     TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('TR040009', 'Western Rail Link to Heathrow', 'TR04 - Railways',
        'Approximately 800m east of Langley Railway Station to Heathrow Airport Terminal 5', 1,
        'Network Rail Infrastructure Limited', 'Malcolm', 'Parsons', 'webteam@planninginspectorate.gov.uk', '', NULL,
        'Heathrow is the UK\'s busiest airport and handles the most international passengers of any airport in the world. Whilst the London Underground and Heathrow Express services have improved connections to central London, there are limited options for rail passengers travelling to Heathrow Airport from other than London. The Western Rail Access to Heathrow project will create a new connection with the nearby Great Western Mainline (GWML), providing a more direct rail route for passengers travelling to and from Reading, Oxford, South Wales, Bristol, Midlands and beyond. The Network Rail Draft CP5 Enhancements Delivery Plan which has been published for consultation sets out the outputs, scope and milestones required to be delivered by the planned enhancement programme in CP5 (2014 - 2019). The specific project output of this scheme is to improve access and rail connectivity to Heathrow Airport for both travelling customers and the airport\'s workforce by providing interchange at Reading, thereby avoiding the need to travel via London when travelling from the West.',
        '', NULL, NULL, NULL, 'Q4 2019', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Region', NULL, 503685, 177320, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, 'ShowSubmissionsTab', '51.484830274704, -0.50656858271533', 'South East', NULL,
        NULL, '', '2020-01-21 12:15:16', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2022-11-30 00:00:00', NULL);
INSERT INTO ipclive.wp_ipc_projects(CaseReference, ProjectName, Proposal, ProjectLocation, Stage, PromoterName,
                                    PromoterFirstName, PromoterLastName, ApplicantEmailAddress, ApplicantPhoneNumber,
                                    ApplicantDescriptionOfProject, Summary, ProjectEmailAddress, CaseLeaderName,
                                    Commissioner, AnticipatedDateOfSubmission, AnticipatedSubmissionDateNonSpecific,
                                    DateProjectAppearsOnWebsite, DateOfDCOAcceptance, PromotersPublicity,
                                    DateOfRepresentationPeriodOpen, DateOfRelevantRepresentationClose,
                                    StartDateOfPeriodforCommentsOnRelevantReps,
                                    PeriodOfCommentsOnRelevantRepresentationsEnds, DateOfPreliminaryMeeting,
                                    ConfirmedStartOfExamination, DateDetailedRepresentationsPeriodOpens,
                                    DateDetailedRepresentationsPeriodClose,
                                    DateCommentsOnDetailedRepresentationsPeriodOpens,
                                    DateCommentsOnDetailedRepresentationsClose, DateOfReceivingLIR, DeadlineForLIR,
                                    DateCommentsPeriodofLIROpens, DateCommentsPeriodofLIRCloses,
                                    DateOfNextExaminationHearing, NotesRegardingNextExaminationHearing,
                                    ConfirmedDateOfDecision, Stage5ExtensiontoDecisionDeadline, DateOfRecommendations,
                                    Stage5ExtensiontoRecommendationDeadline, DateProjectWithdrawn, MapZoomLevel,
                                    DescriptionOfLocation, AnticipatedGridRefEasting, AnticipatedGridRefNorthing,
                                    SingleOrLinear, StartGridE, StartGridN, MiddleGridE, MiddleGridN, EndGridE,
                                    EndGridN, Documents, LatLong, Region, DateOfDCOSubmission,
                                    DateOfDCOAcceptance_NonAcceptance, WebAddress, Modified, DateRRepAppearOnWebsite,
                                    DateOfCommissionerAppointment, DateTimeExaminationEnds,
                                    Stage4ExtensiontoExamCloseDate, TimeOfRelevantRepresentationClose,
                                    TwitterAccountName, SINumber, sourceSystem, dateOfNonAcceptance, CaseSubType)
VALUES ('EN010085', 'Cleve Hill Solar Park', 'EN01 - Generating Stations',
        'Land approximately 2 km northeast of Faversham and 5 km west of Whitstable on the North Kent Coast.', '7',
        'Cleve Hill Solar Park Ltd', 'Removed', 'Removed', 'removed', 'Removed', NULL,
        'Solar photovoltaic array, and electrical storage and connection infrastructure, with a generation capacity of greater than 50 MW',
        'NIEnquiries@planninginspectorate.gov.uk', NULL, NULL, NULL, 'Q4 2018', NULL, NULL, NULL, '2018-12-19',
        '2019-1-28', NULL, NULL, '2019-5-30', '2019-5-30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        '2020-5-28', NULL, '2020-2-28', NULL, NULL, 'Region', NULL, '603781', '163999', NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, 'repsremoved', '51.337996813539, 0.92598581618291', 'South East', '2018-11-16', '2018-12-14',
        'Removed', '2021-12-08 12:00', '2019-1-30', NULL, '2019-11-30 0:00', NULL, NULL, NULL, NULL, 'HORIZON',
        '2022-11-30 00:00:00', NULL);
