CREATE TABLE ipclive.wp_ipc_representations (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ProjectName` text,
  `CaseReference` varchar(10) DEFAULT NULL,
  `DataID` int(11) DEFAULT NULL,
  `UniqueReference` varchar(32) NOT NULL,
  `WebReference` int(11) DEFAULT NULL,
  `PersonalName` text,
  `Representative` varchar(255) DEFAULT NULL,
  `IndvdlOnBhalfName` text,
  `OrgOnBhalfName` text,
  `AgentOrgOnBhalfContactName` text,
  `RepFrom` varchar(200) DEFAULT NULL,
  `InterestInLand` text,
  `SpecifyOther` text,
  `CompulsoryAcquisitionHearing` text,
  `RepresentationOriginal` text,
  `RepresentationRedacted` text,
  `RelevantOrNot` text,
  `SubmitFurtherWrittenReps` text,
  `PreliminaryMeeting` text,
  `OpenFloorHearings` text,
  `IssuesSpecificHearings` text,
  `DateRrepReceived` datetime DEFAULT NULL,
  `DoNotPublish` varchar(5) DEFAULT NULL,
  `Attachments` text,
  PRIMARY KEY (`ID`),
  KEY `Date` (`DateRrepReceived`),
  KEY `CaseReference` (`CaseReference`),
  KEY `UniqueReference` (`UniqueReference`),
  KEY `RepFrom` (`RepFrom`)
);

INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (2,'SPT Feb 2020','EN010009',NULL,'WS010006-34601',NULL,'Test (Test)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comment which exceeds the character limit.  Clearly there is much to be said which must not be left unsaid.  Even if it turns out I''m the only one to have said, no-one will be able to exclaim "You should have said!"',NULL,NULL,NULL,NULL,NULL,'2020-02-19 00:00:00',NULL,'WS010006-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (3,'regression test','EN010009',NULL,'BC010012-34602',NULL,'neil frost (neil frost )',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-02-28 00:00:00',NULL,'BC010012-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (4,'Edge Reg Test 1.4','TR033002',NULL,'uniqueReference',NULL,'Suzan Smith',NULL,NULL,NULL,NULL,'Myself',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-02-03 00:00:00',NULL,'TR033002-000027');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (5,'1.4 Reg Test','EN010009',NULL,'WW010005-34611',NULL,'Frosty (Frosty )',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-09-03 00:00:00',NULL,'WW010005-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (6,'Letters Test','EN010009',NULL,'WW010007-34616',NULL,'Frosty (Frosty)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-03-19 00:00:00',NULL,'WW010007-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (7,'Horizon 45 release','EN010009',NULL,'BC010013-34618',NULL,'Frosty Fear (Frosty Fear )',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-01-04 00:00:00',NULL,'BC010013-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (8,'Reg 1.5 on Firefox','EN010009',NULL,'TR043003-000010',NULL,'champ kadaba',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-04-29 00:00:00',NULL,'TR043003-000011');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (9,'regression test 1.5','EN010009',NULL,'BC010015-34623',NULL,'Fickly finger of feat (Fickly finger of feat )',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-04-29 00:00:00',NULL,'BC010015-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (10,'Accessibility Testing','EN010009',NULL,'EN010113-34637',NULL,'Frosty Fright Nights (Frosty Fright Nights )',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-08-28 00:00:00',NULL,'EN010113-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (12,'TEST Welsh NSIP','EN010009',NULL,'BC010021-34640',NULL,'OTIB (OTIB)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-07-09 00:00:00',NULL,'BC010021-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (13,'TEST CASE 15/09/2020','EN010009',NULL,'EN010114-34643',NULL,'B&E Testing (B&E Testing)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-09-15 00:00:00',NULL,'EN010114-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (15,'Santosh Test NI','EN010009',NULL,'TR010060-34646',NULL,'Santosh Bhat',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-12-10 00:00:00',NULL,'TR010060-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (16,'Auto_Test','EN010009',NULL,'TR010065-34656',NULL,'No name provided',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-11-17 00:00:00',NULL,NULL);
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (17,'Auto_Test','EN010009',NULL,'TR010065-34657',NULL,'No name provided',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-11-18 00:00:00',NULL,NULL);
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (18,'Website Regression','EN010009',NULL,'BC010027-34658',NULL,'FRIGHT NIGHTS FROSTY (FRIGHT NIGHTS FROSTY)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-12-15 00:00:00',NULL,'BC010027-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (19,'NI Test for Website checks','EN010009',NULL,'TR010093-34660',NULL,'Frosty Fright Nights (Frosty Fright Nights )',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2020-12-16 00:00:00',NULL,'TR010093-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (20,'Auto_Test','EN010009',NULL,'TR010109-34670',NULL,'PINS (PINS)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-08-01 00:00:00',NULL,NULL);
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (21,'Auto_Test','EN010009',NULL,'TR010109-34671',NULL,'Frosty Flights (Frosty Flights)',NULL,NULL,NULL,NULL,'Parish Councils',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-08-01 00:00:00',NULL,'TR010109-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (22,'Frosty Flights','EN010009',NULL,'TR020006-34674',NULL,'Neil (Neil )',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-11-01 00:00:00',NULL,'TR020006-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (23,'Test Energy 2','EN010009',NULL,'EN010117-34690',NULL,'Energy (Energy)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-11-01 00:00:00',NULL,'EN010117-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (24,'ACR034','EN010009',NULL,'BC010033-34717',NULL,'David W',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-03-12 00:00:00',NULL,NULL);
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (25,'HZN Reg 51 Testing','EN010009',NULL,'TR010140-34719',NULL,'Frosty (Frosty)',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-03-13 00:00:00',NULL,'TR010140-000001');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (26,'HZN Reg 51 Testing','EN010009',NULL,'TR010140-34720',NULL,'Frosty Fliers (Frosty Fliers )',NULL,NULL,NULL,NULL,'Parish Councils',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-03-14 00:00:00',NULL,'TR010140-000002');
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (27,'SPT May 2021','EN010009',NULL,'EN010118-34713',NULL,'Neil Frost',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-03-15 00:00:00',NULL,NULL);
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (28,'SPT May 2021','EN010009',NULL,'EN010118-34726',NULL,'Chris Cundill',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-03-16 00:00:00',NULL,NULL);
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (29,'SPT May 2021','EN010009',NULL,'EN010118-34727',NULL,'Chris',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2021-03-17 00:00:00',NULL,NULL);
INSERT INTO ipclive.wp_ipc_representations (`ID`,`ProjectName`,`CaseReference`,`DataID`,`UniqueReference`,`WebReference`,`PersonalName`,`Representative`,`IndvdlOnBhalfName`,`OrgOnBhalfName`,`AgentOrgOnBhalfContactName`,`RepFrom`,`InterestInLand`,`SpecifyOther`,`CompulsoryAcquisitionHearing`,`RepresentationOriginal`,`RepresentationRedacted`,`RelevantOrNot`,`SubmitFurtherWrittenReps`,`PreliminaryMeeting`,`OpenFloorHearings`,`IssuesSpecificHearings`,`DateRrepReceived`,`DoNotPublish`,`Attachments`) VALUES (30,'SPT May 2021','EN010009',NULL,'EN010118-34740',NULL,'Chris Cundill',NULL,NULL,NULL,NULL,'Members of the Public/Businesses',NULL,NULL,NULL,NULL,'Some comments',NULL,NULL,NULL,NULL,NULL,'2022-07-04 00:00:00',NULL,NULL);

