# Deploy NI Redirects

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Test
    values: # there is no dev env for NI
      - Test
      - Prod

# no automatic deployments
trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.16.1

variables:
    - group: ni_directs_deploy_${{ lower(parameters.environment) }}
    - name: azureSubscription
      value: applications-service-${{ lower(parameters.environment) }}
    - name: appName
      value: pins-app-applications-service-applications-api-${{ lower(parameters.environment) }}-ukw-001
    - name: resourceGroup
      value: pins-rg-applications-service-${{ lower(parameters.environment) }}-ukw-001

jobs:
  - deployment: test_and_deploy
    displayName: Test & Deploy
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
            - script: |
                sudo apt-get update
                sudo apt-get install -y jq
              displayName: Install jq
            - task: AzureCLI@2
              displayName: Fetch BACK_OFFICE_API_INTEGRATION_CASE_REFERENCES and store in config
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  RESOURCE_GROUP="${{ variables.resourceGroup }}"
                  APP_NAME="${{ variables.appName }}"

                  # Fetch environment variable
                  CASE_REFERENCES=$(az webapp config appsettings list \
                    --name $APP_NAME \
                    --resource-group $RESOURCE_GROUP \
                    --query "[?name=='BACK_OFFICE_API_INTEGRATION_CASE_REFERENCES'].value" -o tsv)

                  # Parse the variable into a JSON array
                  PARSED_REFERENCES=$(echo $CASE_REFERENCES | tr -d ' ' | jq -R 'split(",")')

                  # Write to JSON file
                  OUTPUT_FILE="./packages/ni-redirects/src/config.generated.${{ lower(parameters.environment) }}.json"
                  echo "{\"redirectAllowedCaseReferences\": $PARSED_REFERENCES}" > $OUTPUT_FILE

                  # Confirm file creation
                  echo "Generated config file: $OUTPUT_FILE"
                  echo "Contents:"
                  cat $OUTPUT_FILE
            - template: steps/node_script.yml@templates
              parameters:
                script: npm ci
                workingDirectory: $(Build.Repository.LocalPath)/packages/ni-redirects
            - template: steps/node_script.yml@templates
              parameters:
                script: npm run test:cov
                workingDirectory: $(Build.Repository.LocalPath)/packages/ni-redirects
            - template: steps/node_script.yml@templates
              parameters:
                script: npm run deploy:${{ lower(parameters.environment) }}
                workingDirectory: $(Build.Repository.LocalPath)/packages/ni-redirects
                environmentVariables:
                  CLOUDFLARE_ACCOUNT_ID: $(CLOUDFLARE_ACCOUNT_ID)
                  CLOUDFLARE_API_TOKEN: $(CLOUDFLARE_API_TOKEN)
    workspace:
      clean: all
