parameters:
  - name: deploymentTag
    type: string
    default: none
  - name: environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test

trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Applications Token
      name: Planning-Inspectorate/common-pipeline-templates
  pipelines:
    - pipeline: forms-web-app-ci
      source: forms-web-app CI
      trigger: 
        branches:
          include: 
            - main

extends:
  template: stages/wrapper_web_app_cd.yml@templates
  parameters:
    appName: pins-app-applications-service-applications-wfe-$(ENVIRONMENT)-uks-001
    artifactSourcePipeline: forms-web-app CI
    azurecrName: $(azurecrName)
    azurecrServiceConnection: $(azurecrServiceConnection)
    deploymentTag: ${{ parameters.deploymentTag }}
    globalVariables:
      - template: pipelines/forms-web-app/variables.yml@self
      - template: pipelines/variables.yml@self  
    projectName: $(projectName) 
    releaseVersion: $(version.MajorMinor)
    repository: $(repository)
    ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'ResourceTrigger') }}:
      environments:
        - name: Dev
    ${{ else }}:
      environments: ${{ parameters.environments }}
