parameters:
  - name: deploymentTag
    type: string
    default: latest
  - name: environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Production
        dependsOn:
          - Test

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - packages/forms-web-app

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Applications Token
      name: Planning-Inspectorate/common-pipeline-templates
      ref: feature/terraform-rename-azure-cli-step

pool:
  vmImage: ubuntu-latest

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Deploy
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/azure_web_app_deploy.yml@templates
            parameters:
              appName: pins-app-applications-service-ni-wfe-$(ENVIRONMENT)-uks-001
              artifactSourcePipeline: forms-web-app CI
              azurecrName: $(azurecrName)
              azurecrServiceConnection: $(azurecrServiceConnection)
              azureEnvironmentServiceConnection: $(projectName)-$[variables.ENVIRONMENT]
              deploymentTag: ${{ parameters.deploymentTag }}
              releaseVersion: $(version.MajorMinor)
              repository: $(repository)
    globalVariables:
      - template: pipelines/forms-web-app/variables.yml@self
      - template: pipelines/variables.yml@self          
    ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
      environments:
        - name: Dev
    ${{ else }}:
      environments: ${{ parameters.environments }}
