parameters:
  - name: deploymentTag
    type: string
    default: latest
  - name: environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - packages/forms-web-app

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Applications Token
      name: Planning-Inspectorate/common-pipeline-templates
      ref: feature/terraform-rename-azure-cli-step

pool:
  vmImage: ubuntu-latest

extends:
  template: stages/wrapper_web_app_cd.yml@templates
  parameters:
    appName: pins-app-applications-service-ni-wfe-$(ENVIRONMENT)-uks-001
    artifactSourcePipeline: forms-web-app CI
    azurecrName: $(azurecrName)
    azurecrServiceConnection: $(azurecrServiceConnection)
    deploymentTag: ${{ parameters.deploymentTag }}
    globalVariables:
      - template: pipelines/forms-web-app/variables.yml@self
      - template: pipelines/variables.yml@self  
    projectName: $(projectName) 
    releaseVersion: $(version.MajorMinor)
    repository: $(repository)
    ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
      environments:
        - name: Dev
    ${{ else }}:
      environments: ${{ parameters.environments }}
