openapi: 3.0.3
info:
  title: Applications Service API Documentation
  description: API to <ul><li>create, retrieve and modify planning applications</li></ul>
  version: 1.0.4
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3000/' # needs to be variable replaced
paths:
  '/api/v1/applications/{id}':
    get:
      summary: Returns an existing application
      description: description goes here
      tags:
        - Applications
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier
      responses:
        '200':
          description: Returns an application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '404':
          description: The application could not be found
components:
  schemas:
    Application:
      type: object
      properties:
        id:
          type: string
          format: uuid

