@startuml
set separator none
title Applications Back-Office Container

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(ApplicationsFrontOffice, "Applications Front-Office", $descr="External facing service providing ability to participate in the application process for Nationally Significant Infrastructure Projects (NSIPs) within England and Wales", $tags="", $link="")

System_Boundary("ApplicationsBackOffice_boundary", "Applications Back-Office", $tags="") {
  Container(ApplicationsBackOffice.Filestorage, "File storage", $techn="", $descr="", $tags="", $link="")
  Container(ApplicationsBackOffice.BOWeb, "BO Web", $techn="Node.js, Azure Web App", $descr="Back-office website used to manage cases", $tags="", $link="")
  Container(ApplicationsBackOffice.WebBOAPI, "Web BO API", $techn="Node.js, Azure Web App", $descr="", $tags="", $link="")
  ContainerDb(ApplicationsBackOffice.Database, "Database", $techn="Azure SQL", $descr="Source of truth for cases", $tags="", $link="")
}

Rel(ApplicationsFrontOffice, ApplicationsBackOffice.Filestorage, "Sends file for submission", $techn="HTTPS", $tags="", $link="")
Rel(ApplicationsBackOffice.Filestorage, ApplicationsFrontOffice, "Reads published documents files", $techn="", $tags="", $link="")
Rel(ApplicationsBackOffice.BOWeb, ApplicationsBackOffice.WebBOAPI, "Renders page, gets and posts data using", $techn="HTTPS, JSON", $tags="", $link="")
Rel(ApplicationsBackOffice.WebBOAPI, ApplicationsBackOffice.Database, "Reads and writes case data to", $techn="", $tags="", $link="")
Rel(ApplicationsBackOffice.WebBOAPI, ApplicationsFrontOffice, "Broadcasts message on Advice changes", $techn="Azure Service via topic s51-advice", $tags="", $link="")

SHOW_LEGEND(true)
@enduml