const applicationsDataFixture = [
	{
		CaseReference: 'mock case reference 1',
		ProjectName: 'mock project name 1',
		Proposal: 'mock proposal 1',
		Summary: 'mock summary 1',
		Stage: 1,
		PromoterName: 'mock promoter first name 1 mock promoter last name 1',
		PromoterFirstName: 'mock promoter first name 1',
		PromoterLastName: 'mock promoter last name 1',
		ApplicantEmailAddress: 'mock applicant email address 1',
		ApplicantPhoneNumber: 'mock applicant phone number 1',
		WebAddress: 'mock web address 1',
		ProjectEmailAddress: 'mock project email address 1',
		Region: 'mock region 1',
		ProjectLocation: 'mock project location 1',
		AnticipatedGridRefEasting: 594934,
		AnticipatedGridRefNorthing: 5636170,
		MapZoomLevel: 0,
		AnticipatedDateOfSubmission: '2020-01-01',
		AnticipatedSubmissionDateNonSpecific: '',
		DateOfDCOSubmission: '2018-01-01',
		DateOfDCOAcceptance_NonAcceptance: '2019-06-06',
		DateOfPreliminaryMeeting: '2020-01-01',
		ConfirmedStartOfExamination: null,
		DateTimeExaminationEnds: '2021-07-07T00:00:00.000Z',
		DateOfRepresentationPeriodOpen: '2019-05-06',
		DateOfRelevantRepresentationClose: '2019-05-06',
		DateRRepAppearOnWebsite: '2019-06-06',
		Stage4ExtensiontoExamCloseDate: null,
		stage5ExtensionToRecommendationDeadline: null,
		Stage5ExtensiontoDecisionDeadline: null,
		DateOfRecommendations: null,
		ConfirmedDateOfDecision: null,
		DateProjectWithdrawn: null,
		sourceSystem: 'mock source system 1',
		dateOfNonAcceptance: '2019-06-06T00:00:00.000Z',
		LongLat: [' -11.543792740342', '100.58954279911']
	},
	{
		CaseReference: 'mock case reference 2',
		ProjectName: 'mock project name 2',
		Proposal: 'mock proposal 2',
		Summary: 'mock summary 2',
		Stage: 2,
		PromoterName: 'mock promoter first name 2 mock promoter last name 2',
		PromoterFirstName: 'mock promoter first name 2',
		PromoterLastName: 'mock promoter last name 2',
		ApplicantEmailAddress: 'mock applicant email address 2',
		ApplicantPhoneNumber: 'mock applicant phone number 2',
		WebAddress: 'mock web address 2',
		ProjectEmailAddress: 'mock project email address 2',
		Region: 'mock region 2',
		ProjectLocation: 'mock project location 2',
		AnticipatedGridRefEasting: 64756,
		AnticipatedGridRefNorthing: 745764,
		MapZoomLevel: 0,
		AnticipatedDateOfSubmission: null,
		AnticipatedSubmissionDateNonSpecific: null,
		DateOfDCOSubmission: null,
		DateOfDCOAcceptance_NonAcceptance: null,
		DateOfPreliminaryMeeting: null,
		ConfirmedStartOfExamination: '2020-03-30',
		DateTimeExaminationEnds: '2020-04-14T12:00:00.000Z',
		DateOfRepresentationPeriodOpen: '2020-03-30',
		DateOfRelevantRepresentationClose: '2020-04-10',
		DateRRepAppearOnWebsite: '2020-04-14',
		Stage4ExtensiontoExamCloseDate: null,
		stage5ExtensionToRecommendationDeadline: null,
		Stage5ExtensiontoDecisionDeadline: null,
		DateOfRecommendations: null,
		ConfirmedDateOfDecision: null,
		DateProjectWithdrawn: null,
		sourceSystem: 'mock source system 2',
		dateOfNonAcceptance: '2022-11-30T00:00:00.000Z',
		LongLat: [' -7.4472854473807', '56.484360139339']
	}
];

module.exports = {
	applicationsDataFixture
};
