BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Document] ALTER COLUMN [version] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Document] ALTER COLUMN [filename] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Document] ALTER COLUMN [originalFilename] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Document] ALTER COLUMN [size] INT NULL;
ALTER TABLE [dbo].[Document] ALTER COLUMN [documentURI] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Document] ALTER COLUMN [dateCreated] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
