const APPLICATION_DB = {
	id: 13,
	caseId: 82,
	caseReference: 'EN0110004',
	projectName: 'Drax Bioenergy with Carbon Capture and Storage Project',
	projectDescription:
		'Drax Power Limited proposes to install post-combustion capture technology that would capture carbon dioxide emissions from up to two of the existing biomass units at Drax Power Station. The proposal includes the construction and operation of carbon capture technology and associated equipment, and the integration of the units into the existing Common Services at Drax Power Station. The proposal includes associated development.',
	publishStatus: 'published',
	sector: 'EN - Energy',
	projectType: 'EN01 - Generating Stations',
	sourceSystem: 'ODT',
	stage: 'pre_application',
	projectLocation: 'Drax Power Station, North Yorkshire',
	projectEmailAddress: 'drax.project.email@example.org',
	regions: 'yorkshire_and_the_humber',
	transboundary: null,
	easting: 485899,
	northing: 414508,
	welshLanguage: 0,
	mapZoomLevel: 'region',
	secretaryOfState: null,
	dateProjectAppearsOnWebsite: null,
	dateOfDCOAcceptance: null,
	anticipatedDateOfSubmission: '2023-09-01 00:00:00.0000000',
	anticipatedSubmissionDateNonSpecific: 'Q3 2023',
	dateOfDCOSubmission: null,
	dateOfRepresentationPeriodOpen: null,
	dateOfRelevantRepresentationClose: null,
	dateRRepAppearOnWebsite: null,
	confirmedStartOfExamination: null,
	dateTimeExaminationEnds: null,
	stage4ExtensionToExamCloseDate: null,
	stage5ExtensionToRecommendationDeadline: null,
	dateOfRecommendations: null,
	confirmedDateOfDecision: null,
	stage5ExtensionToDecisionDeadline: null,
	dateProjectWithdrawn: null,
	section46Notification: null,
	datePINSFirstNotifiedOfProject: null,
	screeningOpinionSought: null,
	screeningOpinionIssued: null,
	scopingOpinionSought: null,
	scopingOpinionIssued: null,
	deadlineForAcceptanceDecision: null,
	dateSection58NoticeReceived: null,
	preliminaryMeetingStartDate: null,
	deadlineForCloseOfExamination: null,
	deadlineForSubmissionOfRecommendation: null,
	deadlineForDecision: null,
	jRPeriodEndDate: null,
	extensionToDateRelevantRepresentationsClose: null,
	examinationTimetableId: null,
	createdAt: '2023-04-14 15:52:45.9033333',
	modifiedAt: '2023-04-18 09:43:07.3020000'
};

const APPLICATION_FO = {
	CaseReference: 'EN010116',
	ProjectName: 'North Lincolnshire Green Energy Park',
	Proposal: 'EN01 - Generating Stations',
	Summary:
		'The Project consists of an Energy Recovery Facility (ERF) converting up to 650,000 tonnes per annum of Refuse Derived Fuel (RDF) to generate a maximum of 95 Mega Watts of electrical output (MWe) and/or 380 Mega Watts of thermal output (MWt) to provide power, heat and steam on the site of the operating Flixborough Wharf on the River Trent. The Project will incorporate battery storage, hydrogen production from the electrolysis of water, hydrogen storage, heat and steam storage. It will also include heat-treatment of bottom and fly ash, concrete block manufacturing, carbon dioxide capture and utilisation and an extended district heat network of 5km, power and gas network to service the nearby proposed housing development. Development at the site will also include the following associated measures to allow access to and from the site by road, rail or river, with a correspondingly reduced environmental impact: i. an extension to Flixborough Wharf; ii. the reopening of a 9km single track railway line that connects Flixborough Wharf with the steel works at Scunthorpe; iii. a railhead complex to handle the RDF and concrete products; and iv. a new road alignment to facilitate the flow of traffic accessing the site from the south.',
	PromoterName: 'North Lincolnshire Green Energy Park Limited',
	PromoterFirstName: '',
	PromoterLastName: '',
	ApplicantEmailAddress: 'chris.bungay@planninginspectorate.gov.uk',
	ApplicantPhoneNumber: '',
	WebAddress: 'https://northlincolnshiregreenenergypark.co.uk/',
	ProjectEmailAddress: 'webteam@planninginspectorate.gov.uk',
	Region: 'Yorkshire and the Humber',
	ProjectLocation: 'Flixborough Wharf, Flixborough Industrial Estate, North Lincolnshire.',
	AnticipatedGridRefEasting: 485899,
	AnticipatedGridRefNorthing: 414508,
	MapZoomLevel: 'Region',
	LatLong: '53.620078025496,-0.70283147423378',
	AnticipatedDateOfSubmission: '0000-00-00',
	AnticipatedSubmissionDateNonSpecific: 'Q3 2021',
	DateOfDCOSubmission: '0000-00-00',
	DateOfDCOAcceptance_NonAcceptance: '0000-00-00',
	DateOfPreliminaryMeeting: '0000-00-00',
	ConfirmedStartOfExamination: '0000-00-00',
	DateTimeExaminationEnds: null,
	DateOfRepresentationPeriodOpen: '0000-00-00',
	DateOfRelevantRepresentationClose: '2024-08-01',
	DateRRepAppearOnWebsite: '0000-00-00',
	Stage4ExtensiontoExamCloseDate: '0000-00-00',
	stage5ExtensionToRecommendationDeadline: '0000-00-00',
	Stage5ExtensiontoDecisionDeadline: '0000-00-00',
	DateOfRecommendations: '0000-00-00',
	ConfirmedDateOfDecision: '0000-00-00',
	DateProjectWithdrawn: '0000-00-00',
	sourceSystem: null,
	dateOfNonAcceptance: null
};

module.exports = {
	APPLICATION_DB,
	APPLICATION_FO
};
