trigger: none

pr: none

resources:
  pipelines:
    - pipeline: terraform-ci
      source: Infrastructure PR
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.25.1

extends:
  template: pipelines/terraform_plan_apply.yml@templates
  parameters:
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Training
        dependsOn:
          - Test
      - name: Prod
        dependsOn:
          - Test
    serviceConnectionPrefix: Azure DevOps Pipelines - Applications Front Office - Infrastructure
    storageAccountName: pinssttfstateuksappserfo
    resourceGroupName: pins-rg-shared-terraform-uks
    containerPrefix: terraform-state-applications-front-office-
    workingDirectory: $(Build.Repository.LocalPath)/infrastructure
    environmentVarFilePath: $(Build.Repository.LocalPath)/infrastructure/environments
    preliminarySteps:
      - task: DownloadSecureFile@1
        name: downloadBlacklistFile
        displayName: 'Download IP blacklist file'
        inputs:
          secureFile: 'ip_blacklist.json'
          retryCount: 3
      - script: |
          echo "Default working directory: $(System.DefaultWorkingDirectory)"
          echo "Reading ip_blacklist.json..."
          if [ -f "$(downloadBlacklistFile.secureFilePath)" ]; then
            echo "File exists. Copying ip_blacklist.json..."
            echo "command: cp $(downloadBlacklistFile.secureFilePath) $(System.DefaultWorkingDirectory)/ip_blacklist.json"
            cp $(downloadBlacklistFile.secureFilePath) $(System.DefaultWorkingDirectory)/ip_blacklist.json
          else
            echo "File does not exist. Skipping copy."
          fi
        displayName: 'Copy IP blacklist file'
